= Łukasz Kusek

*Phone*: (44) 777 420 1310 +
*Email*: lukasz-cv@kusek.info +
*GitHub*: https://github.com/lukasz-kusek +
*LinkedIn*: http://pl.linkedin.com/pub/%C5%82ukasz-kusek/51/b4a/1b9/en +
*Website*: http://lukasz.kusek.info +
*Address*: Harpenden, UK

== Senior Software Engineer

Senior software engineer with over 5 years commercial experience (9 years including part-time jobs). My area of expertise is building highly available backend services on JVM platform (Scala - 1/2 year, Java - 5 years).

=== Skills

==== Database
DynamoDB, PostgreSQL, Oracle, MySQL, 

==== Language
Scala, Java, Python, SQL, Clojure, 

==== Library
Guice, Akka, Spray, Cucumber, CameronFIX, QuickFIX/J, Spring, Hibernate, 

==== Other
REST, JSON, Microservices, Event Sourcing, XML, 

==== Tool
Maven, Git, JIRA, Thoughtworks Go, AWS, 


== Experience

=== Senior Software Engineer (2015-02 - ), Ocado Technology (Online grocery retail), Hatfield, United Kingdom
* I work in an agile team creating microservices providing real time availability logic to inform shoppers what is in and out of stock in milliseconds. Services are designed to be highly available (akka cluster, AWS, blue-green deployment), highly responsible (actor model) and low latency (in-memory cache with akka sharding). Services are based on CQRS and event sourcing.
* I've configured Continuous Delivery pipelines. I've done a research on implementation of BlueGreen Deployment and found major flaws in the early stage what allowed us to prepare architecture of our applications before it's released to production.
* I've worked on replatforming existing order management services to cloud based microservices. I've successfully introduced testing standards in the team (testing levels definitions - unit, component, system tests; naming convention). I've lead sessions to present importance of tests quality.

Technologies: Microservices, JSON, REST, Swagger, Hystrix, PostgreSQL, Python, Cucumber, Mockito, AssertJ, JUnit, Java, Jenkins, Guice, DynamoDB, Crucible, Kibana, Logstash, Thoughtworks Go, AWS, Git, Intellij IDEA, Maven, Scala, ScalaTest, JIRA, Spray, Akka, Event Sourcing, 

=== Senior Software Developer (2014-03 - 2015-01), Luxoft (Investment banking), Krakow, Poland
* Contractor at UBS Investment Bank. I worked on capital commitment, automatic indication of interest generation and trade advertising applications at Cash Equities project.
* I've introduced automatic system tests, enhanced logging that enabled tracking single requests, automatic build system using Gradle and Jenkins which improved speed and reliability of the process.

Technologies: QuickFIX/J, CameronFIX, Spock, Groovy, Git, Gradle, Jenkins, Java, Oracle, JIRA, SVN, Intellij IDEA, SQL, JUnit, AssertJ, Guava, Mockito, 

=== Senior Java Developer (2012-05 - 2014-02), Sabre (Airlines and airports), Krakow, Poland
=== Java Developer Contributor (2011-07 - 2012-04), Sabre (Airlines and airports), Krakow, Poland
* Successfully finished a cost saving project before required deadline. Firstly as a team member, then since 2012 as a team leader. The project was the migration over 30 major airlines between the legacy system (based on HP NonStop Kernel) to the current system. The project was very challenging due to multiple dependencies (Sabre's internal systems, customer's systems), no downtime requirement, big amount of user data (data of 30M+ passengers of airlines), pressure of time, little documentation of the legacy system and all of it's features.
* Developed a library for comparing XMLs. What makes this library different from the other libraries of this type is the possibility of comparing XMLs ignoring the sequence of the elements of the same type. This is very useful if the elements of the same type in an XML represent elements of a set, and the sequence of the elements returned by the system is irrelevant. I've narrowed the problem to an assignment problem and used one of bipartite graph algorithms to solve the root problem.
* Introduced multiple improvements like: automated configuration diffs run by Jenkins, a shared configuration to omit files duplicates, best practices developers meetings, an usage of a pre tested commit, a local SVN slave to speed up read only operations, a global Maven's parent POM for dependencies management and plugins management, an unified configuration API as an abstraction over a configuration source (file, DB, JMX), RESTful monitoring application giving possibility for QAs to test aspects which were not testable before.
* Developed a fully functional application which integrates traveler's Facebook account with a profile stored in Sabre's Customer Profiles. It was done during the HackDay 2013 contest. The application was written in a Clojure.
* Successfully developed within 24 hours a 'proof of concept' application for the HackDay 2012 contest. The idea of the project was to introduce the idea of social media to the world of aviation. The application was written in a Clojure which none of team members didn't know before the contest. The project won the audience award. As a followup of the contest the application has been presented to Sabre's marketing team and it occurred that one of the major Sabre's customer is interested in buying the application.

Technologies: Java, XSLT, Guava, Maven, Apache Wicket, Spring, Hibernate, AspectJ, JUnit, Mockito, Fest, MySQL, Java, MyBatis, Apache Camel, XPath, XML, XML Schema, Oracle, Clojure, 

=== Java Developer (2010-06 - 2011-06), Sylogic (Websites), Warszawa, Poland
* I've been developing web applications for customers. I took part of whole process of creating application (gathering requirements, analysis, designing, developing and deployment)

Technologies: Java, Spring, Hibernate, JSF, Maven, Apache Wicket, Tiles, Intellij IDEA, 

=== Linux administrator (2006-01 - 2009-07), ConSol* Consulting &amp; Solutions Software Poland (CRM), Krakow, Poland
* I've built and been maintaining infrastructure for a technology company which employed 30 developers.
* Developed income optimizer for hospitals. Successfully deployed at the hospital in Sucha Beskidzka.
* Researched and developed a 'proof of concept' application WebCTI - Asterisk / ConSol* CM in a single person R&amp;D project.

Technologies: Linux, Bash, awk, Java, Apache Wicket, Spring, Hibernate, Maven, Intellij IDEA, 


== Recommendations
"Working with Łukasz is a real pleasure. Extreme attention to details, always willing to help others, very fast at providing reliable development results. His technical knowledge is very good, allowing to propose the best solutions for solving problems. He's one of the best developers I've met."
Szymon Paluchowski, April 7, 2013

"Łukasz has proven to be one of the most valuable team members, with his wide technical knowledge, willingness to learn and - especially - unbelievable attention to details. Łukasz always aimed for the complete, perfect solution to a problem - half-measures never satisfied him. I would gladly work with him again."
Maciej Hamiga, January 6, 2013


== Learning

=== Education

AGH University of Science and Technology in Cracow (2004 - 2009), Computer Science


=== Conferences / trainings

Uncle Bob's Advanced TDD (2015)

GeeCon (2014)

JDD (2013)

Java Developers’ Day (2008)

Java Developers’ Day (2006)


=== Other

Currently learning Scala and Clojure.

